

#define SNACK					1		//小吃
#define DRINK					2		//饮料
#define ENTREE					3		//主菜

#define WINDOW_MAX_WIDTH		160		//窗口最大宽度
#define WINDOW_MAX_HIGHT		38		//窗口最大高度

#define INIT_BOARD_COUNT		30		//初始化最大餐桌数量

#define FOODMENU_OUPUT_POSITION_X	WINDOW_MAX_WIDTH-48	//主菜单输出位置X坐标
#define FOODMENU_OUPUT_POSITION_Y	4					//主菜单输出位置Y坐标


#define ADD_WAITER				1
#define DEL_WAITER				0
#define SET_WAITER				2

// 前景色		
#define FOREGROUND_YELLOW		FOREGROUND_GREEN | FOREGROUND_RED						// 黄色
#define FOREGROUND_WHITE		FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED		// 白色
#define FOREGROUND_PURPLE		FOREGROUND_RED | FOREGROUND_BLUE						// 紫色
#define FOREGROUND_CYAN			FOREGROUND_BLUE | FOREGROUND_GREEN						// 青色

// 背景色
#define BACKGROUND_YELLOW		BACKGROUND_GREEN | BACKGROUND_RED						// 黄色
#define BACKGROUND_WHITE		BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_RED		// 白色
#define BACKGROUND_PURPLE		BACKGROUND_RED | BACKGROUND_BLUE						// 紫色
#define BACKGROUND_CYAN			BACKGROUND_BLUE | BACKGROUND_GREEN						// 青色
